version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: lujos-postgres
    restart: always
    environment:
      POSTGRES_USER: lujos_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lujos_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
